disable_changelog = true
branch_whitelist = ["main", "release/*"]
skip_ci = "[skip ci]"
pre_bump_hooks = [
    "cargo build --release",
    "echo 'bumping from {{latest}} to {{version}}'",
    "cargo bump {{version}}",
]
