[package]
name = "monotax_dbo"
version = "0.1.0"
edition = "2021"

[dependencies]
monotax_core = { path = "../monotax_core/" }

anyhow = "1"
chrono = "0.4"
csv = "1.3"
encoding_rs = "0.8.33"
encoding_rs_rw = "0.4.2"
